### ISSUE TITLE
Behavior can't find attribute

### ISSUE THREAD

**Issue by mcki0127** [sadovojav/yii2-image-cutter#2]
Hi, I'm sorry to start an issue for this, but I'm stuck.
I have installed this extension, and I can upload an image and use the cropper tool, but the image will not save.  It throws an "Invalid Parameter: Attribute name must contain word characters only" because $this->attribute in the upload method of the behavior class contains a NULL value.  I have posted this problem in the Yii forum: http://www.yiiframework.com/forum/index.php/topic/70306-trouble-with-behavior/.  Have you come across this and what am I doing wrong?  Thanks much for any help!

**Comment by sadovyiov** [comment]
Hey! I create new release 2.1 this this code (attributes in behaviour).
I upload last commit, and this code was only in dev-master branch.
Update module and try again.
If you will have bug after update, write me.

**Comment by mcki0127** [comment]
That solved the problem.  Thank you!  I love this extension.

**Comment by mcki0127** [comment]
This is probably a dumb question, but what is the best way to pass the meta information of the cropped image back to the model that triggered the before insert event?

**Comment by mcki0127** [comment]
The behavior model only includes non-db attributes.  It doesn't recognize db attributes.  Is this a problem with my configuration?  How can I store the cropped image path in the db?  Thanks for any help!

**Comment by sadovyiov** [comment]
@mcki0127 if you want to save cropped image path, you must use db attributes, if I understand you correctly. The field in db must have string type (char/vchar/text etc.)

**Comment by mcki0127** [comment]
@sadovojav Thanks for your response.  Yes, I do want to use the db attributes, but they don't show up when I do `var_print($this)` from CutterBehavior.php.  The only attributes I see are variables that I have declared in the model.  The cutter behavior does not recognize any db attributes.  I have had image upload and save working just fine prior to installing the cropper extension, so I know my model and db are working fine.

**Comment by sadovyiov** [comment]
@mcki0127 show me your model, pls

**Comment by mcki0127** [comment]
@sadovojav [https://gist.github.com/mcki0127/6d91bb39f26cec23a1784affab1e9b96]

The upload, crop, and save works just fine.  I just have trouble saving the path to db from within the behavior class.

**Comment by mcki0127** [comment]
@sadovojav I'm sorry to be a bother, but do you have any thoughts about the model?  Thanks again!

**Comment by sadovyiov** [comment]
@mcki0127 Hey. You did not use db attributes. If you want save path to DB, you must add this field to DB and use it. But you have internal attributes:

``` php
public $image1File;                                                                            
public $image1Path;                                                                             
public $image2File;                                                                          
public $image2Path;   
```

This extension can not save result path to DB, because you used this attributes. IMHO
In this page I added answer, and example of my model (https://gist.github.com/mcki0127/6d91bb39f26cec23a1784affab1e9b96)

**Comment by mcki0127** [comment]
@sadovojav Awesome.  That works.  Sorry for being so dense.  I was thinking that I had to use internal variables since the uploaded image is an object and the db attribute is a VARCHAR. That's the way I handled it before implementing this extension.
