### ISSUE TITLE
need demo

### ISSUE THREAD

**Issue by wblbird** [sadovojav/yii2-image-cutter#3]
it  can not   upload  cutter image

here is my code：

namespace backend\models;
use Yii;
use sadovojav\cutter\behaviors\CutterBehavior;
class Myform extends \yii\db\ActiveRecord
{    public $imagefile;
    public function behaviors()
    {        return [
            'imagefile' => [
                'class' => CutterBehavior::className(),
                'attributes' => 'imagefile',
                'baseDir' => '/uploads/crop',
                'basePath' => '@webroot',
            ],       ];    }
 public function rules()
    {
        return [
            ['imagefile', 'file', 'extensions' => 'jpg, jpeg, png', 'mimeTypes' => 'image/jpeg, image/png'],
        ];    }
 public function attributeLabels()
    {        return [  
            'image'=>'image',
            'imagefile'=>'imagefile',
##                     ];    }}

  controller：
 public function actionIndex()
    {
       $model = new Myform();
        if (Yii::$app->request->isPost) {
          $model->imagefile = UploadedFile::getInstance($model, 'imagefile');
          $model->imagefile->saveAs('uploads/' . $model->imagefile->baseName . '.' . $model->imagefile->extension);
          $model->image= $model->imagefile->baseName;
          $model->save();
        }
        return $this->render('myform', ['model' => $model]);    
##     }

views：
    <?php 
    $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]);?>
    <?= $form->field($model, 'image')->textInput() ?>
    <?= $form->field($model, 'imagefile')->widget(\sadovojav\cutter\Cutter::className(), [
        //options
    ]); ?>

```
    <div class="form-group">
        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary']) ?>
    </div>
<?php ActiveForm::end(); ?>
```

**Comment by sadovyiov** [comment]
Hey. @wblbird. You do not need add "upload" code to you controller. Look that, this is my work code:

Controller:

``` php
    public function actionCreate()
    {
        $model = new Page();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }
```

Model:

``` php
/**
 * @property string $image
 *
 */

public function behaviors()
    {
        return [
            'image' => [
                'class' => CutterBehavior::className(),
                'attributes' => 'image',
                'baseDir' => '/uploads/crop',
                'basePath' => '@root'
            ],
        ];
    }
```

You must understand next, if you want save result path to DB you must use DB attribute.
1. https://github.com/sadovojav/yii2-image-cutter/issues/2#issuecomment-208275956
2. https://gist.github.com/mcki0127/6d91bb39f26cec23a1784affab1e9b96
