### ISSUE TITLE
Preview image shifted down

### ISSUE THREAD

**Issue by mcki0127** [sadovojav/yii2-image-cutter#4]
Hi @sadovojav, Since I updated to your latest commit I have been having a problem with the preview image inside the blue box.  The span at the top of the box which says "Click to upload image" is pushing the preview image down below that line so that the bottom of the image hangs below the blue box.  I believe the span text should be overlapping the image, correct?  I've turned off all the site css to rule that out.  Is there an easy fix?  Thanks!

<a href="http://tinypic.com?ref=24o67ae" target="_blank"><img src="http://i63.tinypic.com/24o67ae.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by sadovyiov** [comment]
May you inspect the blue box element. It must be as like this - http://take.ms/XMCug
I think only overriding added new style for your span tag in blue box.

**Comment by mcki0127** [comment]
Thank you.  I have it figured out now.
